In [1]:
import procanCorke as pc

DHRobot: Puma560, 6 joints (RRRRRR), dynamics, standard DH parameters
┌────┬──────────┬─────────┬────────┐
│θⱼ  │    dⱼ    │   aⱼ    │   ⍺ⱼ   │
├────┼──────────┼─────────┼────────┤
│ q1 │        0 │  -0.116 │   0.0° │
│ q2 │   0.0294 │       0 │  90.0° │
│ q3 │        0 │    0.23 │ 180.0° │
│ q4 │ -0.00286 │ 0.08173 │  90.0° │
│ q5 │  -0.0904 │  0.0019 │  90.0° │
│ q6 │        0 │  0.0438 │ -90.0° │
└────┴──────────┴─────────┴────────┘

┌─┬──┐
└─┴──┘



In [2]:
T_func(0,0,pi,-pi/2,pi,-pi/2)

NameError: name 'T_func' is not defined

In [3]:
pc.T_func(0,0,pi,-pi/2,pi,-pi/2)

NameError: name 'pi' is not defined

In [4]:
import math

In [5]:
pi = math.pi

In [6]:
pc.T_func(0,0,pi,-pi/2,pi,-pi/2)

array([[-1.00000000e+00,  9.24446373e-33,  2.83276945e-16,
        -4.80200000e-01],
       [-9.41903022e-32, -1.00000000e+00,  1.22464680e-16,
        -2.86000000e-03],
       [ 2.44929360e-16,  1.22464680e-16,  1.00000000e+00,
        -5.04300000e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [7]:
pc.T_func(0,0,0,0,0,0)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.41430000e-01],
       [ 0.00000000e+00,  1.00000000e+00,  2.71834567e-16,
        -2.86000000e-03],
       [ 0.00000000e+00, -2.44929360e-16,  1.00000000e+00,
        -6.10000000e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [8]:
pc.Ts

  ((6.12323399573677e-17*sin(q_3)*sin(q_0 + q_1)*cos(q_2) + 1.22464679914735e-16*sin(q_3)*sin(q_0 + q_1) + 1.0*cos(q_0 + q_1)*cos(q_2 - q_3))*cos(q_4) - 0.5*cos(q_0 + q_1 - q_4) + 0.5*cos(q_0 + q_1 + q_4) - 3.06161699786838e-17*cos(q_0 + q_1 - q_2 - q_4) + 3.06161699786838e-17*cos(q_0 + q_1 - q_2 + q_4) + 3.06161699786838e-17*cos(q_0 + q_1 + q_2 - q_4) - 3.06161699786838e-17*cos(q_0 + q_1 + q_2 + q_4) + 1.87469972832732e-33*cos(q_0 + q_1 - q_3 - q_4) - 1.87469972832732e-33*cos(q_0 + q_1 - q_3 + q_4) + 1.87469972832732e-33*cos(q_0 + q_1 + q_3 - q_4) - 1.87469972832732e-33*cos(q_0 + q_1 + q_3 + q_4) - 1.54074395550979e-33*cos(-q_0 - q_1 + q_2 + q_3 + q_4) + 1.54074395550979e-33*cos(q_0 + q_1 - q_2 - q_3 + q_4) - 1.53080849893419e-17*cos(q_0 + q_1 - q_2 + q_3 - q_4) + 1.53080849893419e-17*cos(q_0 + q_1 - q_2 + q_3 + q_4) + 1.53080849893419e-17*cos(q_0 + q_1 + q_2 - q_3 - q_4) - 1.53080849893419e-17*cos(q_0 + q_1 + q_2 - q_3 + q_4) + 1.54074395550979e-33*cos(q_0 + q_1 + q_2 + q_3 - q_4) - 

In [9]:
pc.M

Matrix([
[ ((6.12323399573677e-17*sin(q_3)*sin(q_0 + q_1)*cos(q_2) + 1.22464679914735e-16*sin(q_3)*sin(q_0 + q_1) + 1.0*cos(q_0 + q_1)*cos(q_2 - q_3))*cos(q_4) - 0.5*cos(q_0 + q_1 - q_4) + 0.5*cos(q_0 + q_1 + q_4) - 3.06161699786838e-17*cos(q_0 + q_1 - q_2 - q_4) + 3.06161699786838e-17*cos(q_0 + q_1 - q_2 + q_4) + 3.06161699786838e-17*cos(q_0 + q_1 + q_2 - q_4) - 3.06161699786838e-17*cos(q_0 + q_1 + q_2 + q_4) + 1.87469972832732e-33*cos(q_0 + q_1 - q_3 - q_4) - 1.87469972832732e-33*cos(q_0 + q_1 - q_3 + q_4) + 1.87469972832732e-33*cos(q_0 + q_1 + q_3 - q_4) - 1.87469972832732e-33*cos(q_0 + q_1 + q_3 + q_4) - 1.54074395550979e-33*cos(-q_0 - q_1 + q_2 + q_3 + q_4) + 1.54074395550979e-33*cos(q_0 + q_1 - q_2 - q_3 + q_4) - 1.53080849893419e-17*cos(q_0 + q_1 - q_2 + q_3 - q_4) + 1.53080849893419e-17*cos(q_0 + q_1 - q_2 + q_3 + q_4) + 1.53080849893419e-17*cos(q_0 + q_1 + q_2 - q_3 - q_4) - 1.53080849893419e-17*cos(q_0 + q_1 + q_2 - q_3 + q_4) + 1.54074395550979e-33*cos(q_0 + q_1 + q_2 + q_3 

In [10]:
from sympy import nsimplify

In [11]:
T06 = nsimplify(pc.Ts,tolerance=1e-4)

RecursionError: maximum recursion depth exceeded while calling a Python object

In [12]:
Pa = np.array([[2],[2],[2],[10]])
Pa = Pa/10

NameError: name 'np' is not defined

In [13]:
import numpy as np
Pa = np.array([[2],[2],[2],[10]])
Pa = Pa/10

In [14]:
pc.M@Pa

Matrix([
[0.08173*(1.0*sin(q_2)*cos(q_0 + q_1) + 6.12323399573677e-17*sin(q_0 + q_1)*cos(q_2) + 1.22464679914735e-16*sin(q_0 + q_1))*sin(q_3) + 0.0904*(1.0*sin(q_2)*cos(q_0 + q_1) + 6.12323399573677e-17*sin(q_0 + q_1)*cos(q_2) + 1.22464679914735e-16*sin(q_0 + q_1))*cos(q_3) - 0.2*(6.12323399573677e-17*sin(q_3)*sin(q_0 + q_1)*cos(q_2) + 1.22464679914735e-16*sin(q_3)*sin(q_0 + q_1) + 1.0*cos(q_0 + q_1)*cos(q_2 - q_3))*sin(q_4) + 0.0019*(6.12323399573677e-17*sin(q_3)*sin(q_0 + q_1)*cos(q_2) + 1.22464679914735e-16*sin(q_3)*sin(q_0 + q_1) + 1.0*cos(q_0 + q_1)*cos(q_2 - q_3))*cos(q_4) - 0.0438*(-(6.12323399573677e-17*sin(q_3)*sin(q_0 + q_1)*cos(q_2) + 1.22464679914735e-16*sin(q_3)*sin(q_0 + q_1) + 1.0*cos(q_0 + q_1)*cos(q_2 - q_3))*cos(q_4) + 0.5*cos(q_0 + q_1 - q_4) - 0.5*cos(q_0 + q_1 + q_4) + 3.06161699786838e-17*cos(q_0 + q_1 - q_2 - q_4) - 3.06161699786838e-17*cos(q_0 + q_1 - q_2 + q_4) - 3.06161699786838e-17*cos(q_0 + q_1 + q_2 - q_4) + 3.06161699786838e-17*cos(q_0 + q_1 + q_2 + q_4) -

In [15]:
T_func(0,0,pi,-pi/2,pi,-pi/2)@Pa

NameError: name 'T_func' is not defined

In [16]:
pc.T_func(0,0,pi,-pi/2,pi,-pi/2)@Pa

array([[-0.6802 ],
       [-0.20286],
       [ 0.14957],
       [ 1.     ]])

In [17]:
pc.T_func(0,0,0,0,0,0)@Pa

array([[0.44143],
       [0.19714],
       [0.139  ],
       [1.     ]])